[window]
opacity = 1.0

padding = { x = 4, y = 4 }

[scrolling]
history = 2000

[font]
size = 10.0

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic" 

[bell]
duration = 0 

[cursor]
style = { shape = "Block", blinking = "Off" }

[colors]

[colors.primary]
background = "#fff9ee"
foreground = "#1e1b13"

[colors.cursor]
text   = "#fff9ee"
cursor = "#6e5d0e"

[colors.selection]
text       = "#e0d9cc"
background = "#6e5d0e"

[colors.normal]
black   = "#4b4739"
red     = "#ba1a1a"
green   = "#6e5d0e"
yellow  = "#43664e"
blue    = "#221b00"
magenta = "#211b04"
cyan    = "#665e40"
white   = "#1e1b13"

[colors.bright]
black   = "#4b4739"
red     = "#ba1a1a"
green   = "#6e5d0e"
yellow  = "#43664e"
blue    = "#221b00"
magenta = "#211b04"
cyan    = "#665e40"
white   = "#1e1b13"