[window]
opacity = 1.0

padding = { x = 4, y = 4 }

[scrolling]
history = 2000

[font]
size = 10.0

[font.normal]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic" 

[bell]
duration = 0 

[cursor]
style = { shape = "Block", blinking = "Off" }

[colors]

[colors.primary]
background = "{{ colors.background.default.hex }}"
foreground = "{{ colors.on_surface.default.hex }}"

[colors.cursor]
text   = "{{ colors.surface.default.hex }}"
cursor = "{{ colors.primary.default.hex }}"

[colors.selection]
text       = "{{ colors.surface_dim.default.hex }}"
background = "{{ colors.primary.default.hex }}"

[colors.normal]
black   = "{{ colors.on_surface_variant.default.hex }}"
red     = "{{ colors.error.default.hex }}"
green   = "{{ colors.primary.default.hex }}"
yellow  = "{{ colors.tertiary.default.hex }}"
blue    = "{{ colors.on_primary_container.default.hex }}"
magenta = "{{ colors.on_secondary_container.default.hex }}"
cyan    = "{{ colors.secondary.default.hex }}"
white   = "{{ colors.on_surface.default.hex }}"

[colors.bright]
black   = "{{ colors.on_surface_variant.default.hex }}"
red     = "{{ colors.error.default.hex }}"
green   = "{{ colors.primary.default.hex }}"
yellow  = "{{ colors.tertiary.default.hex }}"
blue    = "{{ colors.on_primary_container.default.hex }}"
magenta = "{{ colors.on_secondary_container.default.hex }}"
cyan    = "{{ colors.secondary.default.hex }}"
white   = "{{ colors.on_surface.default.hex }}"